services:
  db:
    image: mysql:8.0
    container_name: flowershop_db
    restart: always
    environment:
      MYSQL_DATABASE: flower_shop_db
      # VUI LÒNG THAY ĐỔI MẬT KHẨU NÀY TRONG MÔI TRƯỜNG THỰC TẾ
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      # Mount file database.sql để tự động khởi tạo database khi container chạy lần đầu
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
      # Volume để giữ dữ liệu bền vững sau khi tắt container
      - db_data:/var/lib/mysql

volumes:
  db_data: